// Generated by ChatGPT - reviewed by Victor Manuel Romero - 08-04-2026

// handler.js

// Import required modules
const express = require('express'); // Express framework for building APIs
const router = express.Router(); // Create a router instance to define routes

// Mock conversion rates (in real-world, use an external API or service)
const rates = {
  USD: { EUR: 0.9 },
  EUR: { USD: 1.1 }
};

// Define GET /convert endpoint
router.get('/convert', async (req, res) => {
  try {
    // Extract query parameters from request
    const { from, to } = req.query;

    // ===== Input Validation =====

    // Check if 'from' parameter is missing or empty
    if (!from || from.trim() === '') {
      return res.status(400).json({
        success: false,
        data: null,
        error: "'from' parameter is required"
      });
    }

    // Check if 'to' parameter is missing or empty
    if (!to || to.trim() === '') {
      return res.status(400).json({
        success: false,
        data: null,
        error: "'to' parameter is required"
      });
    }

    // Normalize inputs to uppercase to avoid case-sensitivity issues
    const fromCurrency = from.toUpperCase();
    const toCurrency = to.toUpperCase();

    // ===== Business Logic =====

    // Check if conversion rate exists
    if (!rates[fromCurrency] || !rates[fromCurrency][toCurrency]) {
      return res.status(400).json({
        success: false,
        data: null,
        error: 'Conversion rate not available'
      });
    }

    // Retrieve conversion rate from mock data
    const rate = rates[fromCurrency][toCurrency];

    // Build response data
    const result = {
      from: fromCurrency,
      to: toCurrency,
      rate
    };

    // Send success response
    return res.json({
      success: true,
      data: result,
      error: null
    });

  } catch (err) {
    // ===== Error Handling =====

    // Catch unexpected errors and return standardized response
    return res.status(500).json({
      success: false,
      data: null,
      error: 'Internal server error'
    });
  }
});

// Export router so it can be used in an Express app
module.exports = router;
