// Generated by Claude - reviewed by Victor Manuel Romero - 08-04-2026
// Handler tests for currency conversion endpoint

const request = require('supertest');
const express = require('express');
const { expect } = require('chai');
const handler = require('../../src/api/handler');

describe('Currency Conversion Handler', () => {
  let app;

  // Setup test app before each test
  beforeEach(() => {
    app = express();
    app.use('/api', handler);
  });

  // ===== HAPPY PATH TESTS =====
  describe('Happy Path', () => {
    it('should return conversion rate for valid input USD->EUR', async () => {
      const res = await request(app)
        .get('/api/convert?from=usd&to=eur');

      expect(res.status).to.equal(200);
      expect(res.body.success).to.be.true;
      expect(res.body.data).to.exist;
      expect(res.body.data.from).to.equal('USD');
      expect(res.body.data.to).to.equal('EUR');
      expect(res.body.data.rate).to.equal(0.9);
      expect(res.body.error).to.be.null;
    });

    it('should return conversion rate for valid input EUR->USD', async () => {
      const res = await request(app)
        .get('/api/convert?from=eur&to=usd');

      expect(res.status).to.equal(200);
      expect(res.body.success).to.be.true;
      expect(res.body.data.rate).to.equal(1.1);
    });

    it('should handle uppercase input correctly', async () => {
      const res = await request(app)
        .get('/api/convert?from=USD&to=EUR');

      expect(res.status).to.equal(200);
      expect(res.body.success).to.be.true;
    });
  });

  // ===== ERROR CASES - MISSING PARAMETERS =====
  describe('Missing Parameters', () => {
    it('should return error for missing "from" parameter', async () => {
      const res = await request(app)
        .get('/api/convert?to=eur');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
      expect(res.body.error).to.include('from');
      expect(res.body.data).to.be.null;
    });

    it('should return error for missing "to" parameter', async () => {
      const res = await request(app)
        .get('/api/convert?from=usd');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
      expect(res.body.error).to.include('to');
      expect(res.body.data).to.be.null;
    });

    it('should return error when both parameters are missing', async () => {
      const res = await request(app)
        .get('/api/convert');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
    });
  });

  // ===== ERROR CASES - EMPTY/NULL VALUES =====
  describe('Empty or Null Input', () => {
    it('should return error for empty "from" parameter', async () => {
      const res = await request(app)
        .get('/api/convert?from=&to=eur');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
      expect(res.body.error).to.include('from');
    });

    it('should return error for empty "to" parameter', async () => {
      const res = await request(app)
        .get('/api/convert?from=usd&to=');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
      expect(res.body.error).to.include('to');
    });

    it('should return error for whitespace-only "from" parameter', async () => {
      const res = await request(app)
        .get('/api/convert?from=%20%20&to=eur');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
    });
  });

  // ===== ERROR CASES - INVALID CURRENCIES =====
  describe('Invalid Currencies', () => {
    it('should return error for unsupported currency pair', async () => {
      const res = await request(app)
        .get('/api/convert?from=gbp&to=jpy');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
      expect(res.body.error).to.include('not available');
      expect(res.body.data).to.be.null;
    });

    it('should return error for invalid from currency', async () => {
      const res = await request(app)
        .get('/api/convert?from=abc&to=eur');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
    });

    it('should return error for reverse unsupported conversion (EUR->USD reverse)', async () => {
      const res = await request(app)
        .get('/api/convert?from=gbp&to=usd');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
    });
  });

  // ===== EDGE CASES =====
  describe('Edge Cases', () => {
    it('should handle mixed case input correctly', async () => {
      const res = await request(app)
        .get('/api/convert?from=UsD&to=EuR');

      expect(res.status).to.equal(200);
      expect(res.body.success).to.be.true;
    });

    it('should handle special characters in input gracefully', async () => {
      const res = await request(app)
        .get('/api/convert?from=us$&to=eur');

      expect(res.status).to.equal(400);
      expect(res.body.success).to.be.false;
    });

    it('should return consistent response structure', async () => {
      const res = await request(app)
        .get('/api/convert?from=usd&to=eur');

      expect(res.body).to.have.all.keys('success', 'data', 'error');
      expect(typeof res.body.success).to.equal('boolean');
    });
  });
});
